//auth Action Types
// Create
export const ACCOUNT_CREATION_STARTED = "ACCOUNT_CREATION_STARTED";
export const ACCOUNT_CREATION_SUCCESS = "ACCOUNT_CREATION_SUCCESS";
export const ACCOUNT_CREATION_FAIL = "ACCOUNT_CREATION_FAIL";

//account details
export const ACCOUNT_DETAILS_STARTED = "ACCOUNT_DETAILS_STARTED";
export const ACCOUNT_DETAILS_SUCCESS = "ACCOUNT_DETAILS_SUCCESS";
export const ACCOUNT_DETAILS_FAIL = "ACCOUNT_DETAILS_FAIL";

//Fetch
export const ACCOUNT_FETCH_STARTED = "ACCOUNT_FETCH_STARTED";
export const ACCOUNT_FETCH_SUCCESS = "ACCOUNT_FETCH_SUCCESS";
export const ACCOUNT_FETCH_FAIL = "ACCOUNT_FETCH_FAIL";

//Update
export const ACCOUNT_UPDATE_STARTED = "ACCOUNT_UPDATE_STARTED";
export const ACCOUNT_UPDATE_SUCCESS = "ACCOUNT_UPDATE_SUCCESS";
export const ACCOUNT_UPDATE_FAIL = "ACCOUNT_UPDATE_FAIL";

//Delete
export const ACCOUNT_DELETE_STARTED = "ACCOUNT_DELETE_STARTED";
export const ACCOUNT_DELETE_SUCCESS = "ACCOUNT_DELETE_SUCCESS";
export const ACCOUNT_DELETE_FAIL = "ACCOUNT_DELETE_FAIL";
